

export interface Game {
  id: number;
  pool: string;
  date: string;
  dateObj: string;
  time: string;
  location: string;
  court: string;
  home?: string;
  away?: string;
  homeScore?: number;
  awayScore?: number;
  result?: "W" | "L" | "upcoming";
  isPlayoff?: boolean;
  round?: string;
}

export interface Practice {
  id: number;
  date: string;
  dateObj: string;
  time: string;
  location: string;
}

export interface Standing {
  seed: number;
  team: string;
  w: number;
  l: number;
  t: number;
  pd: number;
  ps: number;
  pa: number;
  isOurTeam: boolean;
}

// Our team is "Connor / Eliot / Nathan"
// Complete game schedule from MasterSports (28 regular season games)
export const GAMES: Game[] = [
  // Past Games (Completed)
  {
    id: 1,
    pool: "Pool 1",
    date: "Sat, Mar 21",
    dateObj: "2026-03-21",
    time: "10:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "Catherine Hancock",
    away: "Connor / Eliot / Nathan",
    homeScore: 20,
    awayScore: 26,
    result: "W",
  },
  {
    id: 2,
    pool: "Pool 2",
    date: "Sat, Mar 21",
    dateObj: "2026-03-21",
    time: "11:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "James McNally",
    away: "Sam Hangafarin",
    homeScore: 24,
    awayScore: 17,
    result: "upcoming",
  },
  {
    id: 3,
    pool: "Pool 3",
    date: "Wed, Mar 25",
    dateObj: "2026-03-25",
    time: "5:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "Jon Ramba",
    away: "Marcus Lee/Derick Chi",
    homeScore: 30,
    awayScore: 29,
    result: "upcoming",
  },
  {
    id: 4,
    pool: "Pool 4",
    date: "Wed, Mar 25",
    dateObj: "2026-03-25",
    time: "6:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    result: "upcoming",
  },
  {
    id: 5,
    pool: "Pool 7",
    date: "Wed, Apr 8",
    dateObj: "2026-04-08",
    time: "5:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    away: "Sam Hangafarin",
    awayScore: 26,
    result: "upcoming",
  },
  {
    id: 6,
    pool: "Pool 6",
    date: "Wed, Apr 8",
    dateObj: "2026-04-08",
    time: "6:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "Jon Ramba",
    away: "Connor / Eliot / Nathan",
    homeScore: 30,
    awayScore: 33,
    result: "W",
  },
  {
    id: 7,
    pool: "Pool 5",
    date: "Sat, Apr 11",
    dateObj: "2026-04-11",
    time: "10:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "James McNally",
    away: "Catherine Hancock",
    homeScore: 18,
    awayScore: 11,
    result: "upcoming",
  },
  {
    id: 8,
    pool: "Pool 8",
    date: "Sat, Apr 11",
    dateObj: "2026-04-11",
    time: "11:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    away: "Marcus Lee/Derick Chi",
    awayScore: 22,
    result: "upcoming",
  },
  // Upcoming Games
  {
    id: 9,
    pool: "Pool 11",
    date: "Wed, Apr 15",
    dateObj: "2026-04-15",
    time: "5:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "Connor / Eliot / Nathan",
    away: "Luke Franey/Naveen Krishnamoorthy",
    result: "upcoming",
  },
  {
    id: 10,
    pool: "Pool 10",
    date: "Wed, Apr 15",
    dateObj: "2026-04-15",
    time: "6:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    away: "James McNally",
    result: "upcoming",
  },
  {
    id: 11,
    pool: "Pool 9",
    date: "Sat, Apr 18",
    dateObj: "2026-04-18",
    time: "10:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    away: "Jon Ramba",
    result: "upcoming",
  },
  {
    id: 12,
    pool: "Pool 12",
    date: "Sat, Apr 18",
    dateObj: "2026-04-18",
    time: "11:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "Connor / Eliot / Nathan",
    away: "Sam Hangafarin",
    result: "upcoming",
  },
  {
    id: 13,
    pool: "Pool 16",
    date: "Wed, Apr 22",
    dateObj: "2026-04-22",
    time: "5:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "Connor / Eliot / Nathan",
    away: "Sam Hangafarin",
    result: "upcoming",
  },
  {
    id: 14,
    pool: "Pool 14",
    date: "Wed, Apr 22",
    dateObj: "2026-04-22",
    time: "6:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "Connor / Eliot / Nathan",
    away: "Jon Ramba",
    result: "upcoming",
  },
  {
    id: 15,
    pool: "Pool 15",
    date: "Sat, Apr 25",
    dateObj: "2026-04-25",
    time: "10:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    away: "James McNally",
    result: "upcoming",
  },
  {
    id: 16,
    pool: "Pool 13",
    date: "Sat, Apr 25",
    dateObj: "2026-04-25",
    time: "11:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "Connor / Eliot / Nathan",
    away: "Luke Franey/Naveen Krishnamoorthy",
    result: "upcoming",
  },
  {
    id: 17,
    pool: "Pool 19",
    date: "Wed, Apr 29",
    dateObj: "2026-04-29",
    time: "5:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "Sam Hangafarin",
    away: "Jon Ramba",
    result: "upcoming",
  },
  {
    id: 18,
    pool: "Pool 18",
    date: "Wed, Apr 29",
    dateObj: "2026-04-29",
    time: "6:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "Connor / Eliot / Nathan",
    away: "Catherine Hancock",
    result: "upcoming",
  },
  {
    id: 19,
    pool: "Pool 17",
    date: "Sat, May 2",
    dateObj: "2026-05-02",
    time: "10:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "Connor / Eliot / Nathan",
    away: "Marcus Lee/Derick Chi",
    result: "upcoming",
  },
  {
    id: 20,
    pool: "Pool 20",
    date: "Sat, May 2",
    dateObj: "2026-05-02",
    time: "11:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "Connor / Eliot / Nathan",
    away: "James McNally",
    result: "upcoming",
  },
  {
    id: 21,
    pool: "Pool 24",
    date: "Wed, May 6",
    dateObj: "2026-05-06",
    time: "5:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "James McNally",
    away: "Jon Ramba",
    result: "upcoming",
  },
  {
    id: 22,
    pool: "Pool 22",
    date: "Wed, May 6",
    dateObj: "2026-05-06",
    time: "6:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "Sam Hangafarin",
    result: "upcoming",
  },
  {
    id: 23,
    pool: "Pool 23",
    date: "Sat, May 9",
    dateObj: "2026-05-09",
    time: "10:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "Connor / Eliot / Nathan",
    away: "Kolt Sakofsky/Grant Clabo",
    result: "upcoming",
  },
  {
    id: 24,
    pool: "Pool 21",
    date: "Sat, May 9",
    dateObj: "2026-05-09",
    time: "11:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "Connor / Eliot / Nathan",
    away: "Catherine Hancock",
    result: "upcoming",
  },
  {
    id: 25,
    pool: "Pool 25",
    date: "Wed, May 13",
    dateObj: "2026-05-13",
    time: "5:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "Connor / Eliot / Nathan",
    away: "Sam Hangafarin",
    result: "upcoming",
  },
  {
    id: 26,
    pool: "Pool 26",
    date: "Wed, May 13",
    dateObj: "2026-05-13",
    time: "6:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    home: "Connor / Eliot / Nathan",
    away: "Marcus Lee/Derick Chi",
    result: "upcoming",
  },
  {
    id: 27,
    pool: "Pool 27",
    date: "Sat, May 16",
    dateObj: "2026-05-16",
    time: "10:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "Connor / Eliot / Nathan",
    away: "James McNally",
    result: "upcoming",
  },
  {
    id: 28,
    pool: "Pool 28",
    date: "Sat, May 16",
    dateObj: "2026-05-16",
    time: "11:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    home: "Connor / Eliot / Nathan",
    away: "Jon Ramba",
    result: "upcoming",
  },
  // Playoffs - TBD
  {
    id: 29,
    pool: "Round 1",
    date: "Wed, May 20",
    dateObj: "2026-05-20",
    time: "4:00 PM",
    location: "Ocean Air Park",
    court: "East Court",
    result: "upcoming",
    isPlayoff: true,
    round: "Round 1",
  },
  {
    id: 30,
    pool: "Round 1",
    date: "Wed, May 20",
    dateObj: "2026-05-20",
    time: "4:00 PM",
    location: "Ocean Air Park",
    court: "West Court",
    result: "upcoming",
    isPlayoff: true,
    round: "Round 1",
  },
  {
    id: 31,
    pool: "Round 1",
    date: "Wed, May 20",
    dateObj: "2026-05-20",
    time: "5:00 PM",
    location: "Ocean Air Park",
    court: "East Court",
    result: "upcoming",
    isPlayoff: true,
    round: "Round 1",
  },
  {
    id: 32,
    pool: "Round 1",
    date: "Wed, May 20",
    dateObj: "2026-05-20",
    time: "5:00 PM",
    location: "Ocean Air Park",
    court: "West Court",
    result: "upcoming",
    isPlayoff: true,
    round: "Round 1",
  },
  {
    id: 33,
    pool: "Round 2",
    date: "Wed, May 27",
    dateObj: "2026-05-27",
    time: "5:15 PM",
    location: "Ocean Air Park",
    court: "East Court",
    result: "upcoming",
    isPlayoff: true,
    round: "Round 2",
  },
  {
    id: 34,
    pool: "Round 2",
    date: "Wed, May 27",
    dateObj: "2026-05-27",
    time: "5:15 PM",
    location: "Ocean Air Park",
    court: "West Court",
    result: "upcoming",
    isPlayoff: true,
    round: "Round 2",
  },
  {
    id: 35,
    pool: "Round 3",
    date: "Sat, May 30",
    dateObj: "2026-05-30",
    time: "9:30 AM",
    location: "Carmel Valley Recreation Center",
    court: "Court 1 (North)",
    result: "upcoming",
    isPlayoff: true,
    round: "Round 3",
  },
];

export const OUR_TEAM = "Connor / Eliot / Nathan";

export const STANDINGS = [
  { seed: 1, team: "Kolt Sakofsky/Grant Clabo", w: 2, l: 0, t: 0, pd: 20, ps: 55, pa: 35, isOurTeam: false },
  { seed: 2, team: "James McNally", w: 2, l: 0, t: 0, pd: 14, ps: 42, pa: 28, isOurTeam: false },
  { seed: 3, team: "Connor / Eliot / Nathan", w: 2, l: 0, t: 0, pd: 9, ps: 59, pa: 50, isOurTeam: true },
  { seed: 4, team: "Marcus Lee/Derick Chi", w: 1, l: 1, t: 0, pd: 8, ps: 51, pa: 43, isOurTeam: false },
  { seed: 5, team: "Jon Ramba", w: 1, l: 1, t: 0, pd: -2, ps: 60, pa: 62, isOurTeam: false },
  { seed: 6, team: "Sam Hangafarin", w: 0, l: 2, t: 0, pd: -12, ps: 43, pa: 55, isOurTeam: false },
  { seed: 7, team: "Catherine Hancock", w: 0, l: 2, t: 0, pd: -13, ps: 31, pa: 44, isOurTeam: false },
  { seed: 8, team: "Luke Franey/Naveen Krishnamoorthy", w: 0, l: 2, t: 0, pd: -24, ps: 22, pa: 46, isOurTeam: false },
];

export interface VideoEntry {
  id: number;
  title: string;
  description: string;
  opponent: string;
  date: string;
  youtubeId: string;
}

export const GAME_VIDEOS: VideoEntry[] = [
  {
    id: 1,
    title: "Game 1 - Video 1",
    description: "Catherine Hancock vs Connor/Eliot/Nathan - Video 1",
    opponent: "Catherine Hancock",
    date: "Sat, Mar 21",
    youtubeId: "dQw4w9WgXcQ",
  },
  {
    id: 2,
    title: "Game 1 - Video 2",
    description: "Catherine Hancock vs Connor/Eliot/Nathan - Video 2",
    opponent: "Catherine Hancock",
    date: "Sat, Mar 21",
    youtubeId: "dQw4w9WgXcQ",
  },
  {
    id: 3,
    title: "Game 2 - Video 1",
    description: "Jon Ramba vs Connor/Eliot/Nathan - Video 1",
    opponent: "Jon Ramba",
    date: "Wed, Apr 8",
    youtubeId: "_2oIIm_9QJQ",
  },
  {
    id: 4,
    title: "Game 2 - Video 2",
    description: "Jon Ramba vs Connor/Eliot/Nathan - Video 2",
    opponent: "Jon Ramba",
    date: "Wed, Apr 8",
    youtubeId: "7tXkJ7yxsa8",
  },
  {
    id: 5,
    title: "Game 2 - Video 3",
    description: "Jon Ramba vs Connor/Eliot/Nathan - Video 3",
    opponent: "Jon Ramba",
    date: "Wed, Apr 8",
    youtubeId: "usGVTVHxJko",
  },
  {
    id: 6,
    title: "Game 2 - Video 4",
    description: "Jon Ramba vs Connor/Eliot/Nathan - Video 4",
    opponent: "Jon Ramba",
    date: "Wed, Apr 8",
    youtubeId: "DXACNsxaSGM",
  },
];

export const PRACTICES: Practice[] = [
  {
    id: 1,
    date: "Fri, Mar 20",
    dateObj: "2026-03-20",
    time: "4:00 PM",
    location: "Carmel Valley Recreation Center",
  },
  {
    id: 2,
    date: "Wed, Mar 27",
    dateObj: "2026-03-27",
    time: "4:00 PM",
    location: "Carmel Valley Recreation Center",
  },
  {
    id: 3,
    date: "Wed, Apr 3",
    dateObj: "2026-04-03",
    time: "4:00 PM",
    location: "Carmel Valley Recreation Center",
  },
  {
    id: 4,
    date: "Wed, Apr 10",
    dateObj: "2026-04-10",
    time: "4:00 PM",
    location: "Carmel Valley Recreation Center",
  },
  {
    id: 5,
    date: "Wed, Apr 17",
    dateObj: "2026-04-17",
    time: "4:00 PM",
    location: "Carmel Valley Recreation Center",
  },
  {
    id: 6,
    date: "Wed, Apr 24",
    dateObj: "2026-04-24",
    time: "4:00 PM",
    location: "Carmel Valley Recreation Center",
  },
];

export const ROSTER = [
  { id: 1, name: "Connor", position: "Guard" },
  { id: 2, name: "Eliot", position: "Forward" },
  { id: 3, name: "Nathan", position: "Guard" },
];
